### ISSUE TITLE
Memory leak in searchWithXPathQuery?

### ISSUE THREAD

**Issue by Jateko** [topfunky/hpple#67]
Hi! So i'm am using this cool lib in my app to parse html. it works fine, but i found out a memory leak, each time i use searchWithXPathQuery. i've search all internet, but still have leaks. 

in xcode Instruments in table with leaked objects : 

Responsible library - libxml2.2.dylib
Responsible frame - xmlStrndup

**Comment by topfunky** [comment]
This has been fixed in pull request #80
